### ISSUE TITLE
Using force reply/creating step by step flows

### ISSUE THREAD

**Issue by HemalR** [jmendeth/node-botgram#11]
I can't seem to get forceReply to work :/

```Javascript
bot.command('CommandName', (msg, reply) => {
	const { id } = msg.user;
	reply
		.keyboard([['Option1','Option2']])
		.forceReply() //Tried force() | force_reply() | forceReply(true)
		.text(`Would you like option 1 or 2?`)
});

bot.text(function (msg, reply) {
	console.log(msg);
	console.log(msg.reply); //Get undefined, no matter what variation I try
	reply.text(`Bot replying to a forced reply...`);
});
```

I must be doing something obviously wrong. Does anyone have any pointers?

Or is there any other way to create a step by step conversation flow (where I can hold conversation state between back and forth messages?)

---

Ps - Cheers for the easy to use library!

Edit - Added javascript in markdown

**Comment by HemalR** [comment]
Ok so, reading the docs, I came across: https://core.telegram.org/bots/api#sendmessage where it mentions the keyboard and force reply clash.

Then tried some adjusted code where the keyboard is removed beforehand...

```Javascript
bot.callback((query, next)=>{
	if (query.data === 'Matched string') {
		const { id } = query.message.user;
		const reply = bot.reply(id);
		reply.keyboard();
		reply.text('What is the reply to this message?').forceReply();
	} else {
		return next()
	}
});
```

Still no luck. I suspect it may be because you can only send a single 'reply' via the bot callback (because sending a query.answer after a reply also throws an error). Hmmm...

**Comment by jmendeth** [comment]
ForceReply is intended for groups. Bots that have [privacy mode](https://core.telegram.org/bots#privacy-mode) enabled won't be able to see simple text messages (i.e. «Option1») unless those messages are a reply for the bot. By forcing a reply, you ensure the bot will get the message.

That's probably why ForceReply only works on groups. If you're in a direct chat, forcing a reply is pointless since you'll get the text, whether you use it or not.

So, your initial snippet works as expected on a group (screenshot of Telegram Desktop):

![group bot example](https://user-images.githubusercontent.com/1177304/27551601-52b67698-5aa4-11e7-9731-2a5b611667d1.png)

Note: The `const { id } = msg.user;` line crashes on a group, you should use `msg.chat` or `msg.from` unless you're sure it's a user.

Note: Remember to *remove the keyboard* when it's no longer needed by doing `.keyboard()`, i.e.:

~~~ js
reply.keyboard().text(`Bot replying to a forced reply...`);
~~~

See the [hasher.js example](https://github.com/jmendeth/node-botgram/blob/master/examples/hasher.js) for more info.

**Comment by jmendeth** [comment]
But all of this is irrelevant for mantaining flow; you don't need ForceReply or anything for that.

For info about maintaining flow, see [the end of this section](https://github.com/jmendeth/node-botgram/blob/master/docs/handlers.md#miscellaneous) and the hasher.js example. (Note that in a real application, you'd use a DB instead.)

**Comment by HemalR** [comment]
Ah got it, that explains that. 

Read and forgot about the whole context object when going through the docs. Poor effort on my part.

It will work perfectly in conjunction with a database.

Cheers @jmendeth !!
